version: 0.2


phases:
  pre_build:
    commands:
      - mvn clean install
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=699606088333.dkr.ecr.ap-south-1.amazonaws.com/testing-ecrrepo
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t testing-ecrrepo .
      - docker tag testing-ecrrepo:latest 699606088333.dkr.ecr.ap-south-1.amazonaws.com/testing-ecrrepo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 699606088333.dkr.ecr.ap-south-1.amazonaws.com/testing-ecrrepo:latest
      - docker push 699606088333.dkr.ecr.ap-south-1.amazonaws.com/testing-ecrrepo:latest
      - echo Writing image definitions file...
      - printf '[{"name":"order-service","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
   - imagedefinitions.json
   - target/order-service.jar

